-- Consignas
-- Clientes
-- 1.¿Cuántos clientes existen?

-- 2.¿Cuántos clientes hay por ciudad?
-- Facturas
-- 1.¿Cuál es el total de transporte?
-- 2.¿Cuál es el total de transporte por EnvioVia (empresa de envío)?
-- 3.Calcular la cantidad de facturas por cliente. Ordenar descendentemente por
-- cantidad de facturas.
-- 4.Obtener el Top 5 de clientes de acuerdo a su cantidad de facturas.
-- 5.¿Cuál es el país de envío menos frecuente de acuerdo a la cantidad de facturas?
-- 6.Se quiere otorgar un bono al empleado con más ventas. ¿Qué ID de empleado realizó más operaciones de ventas?
-- Factura detalle
-- 1.¿Cuál es el producto que aparece en más líneas de la tabla Factura Detalle?
-- 2.¿Cuál es el total facturado? Considerar que el total facturado es la suma de cantidad
-- por precio unitario.
-- 3.¿Cuál es el total facturado para los productos ID entre 30 y 50?
-- 4.¿Cuál es el precio unitario promedio de cada producto?
-- 5.¿Cuál es el precio unitario máximo?